const KEY='vialwise_v5';
const $=s=>document.querySelector(s); const $$=s=>[...document.querySelectorAll(s)];
let db=JSON.parse(localStorage.getItem(KEY)||'null')||{settings:{journey:'GLP-1 weight journey',delivery:'Reconstituted vial',units:'kg'},vials:[],schedule:[],weights:[],foods:[],logs:[],compounds:[]};
const save=()=>{localStorage.setItem(KEY,JSON.stringify(db));render()};
const money=n=>'£'+(Number(n)||0).toFixed(2); const id=()=>Date.now().toString(36)+Math.random().toString(36).slice(2,7);
function formObj(form){return Object.fromEntries(new FormData(form).entries())}
function num(v){return Number(v)||0}
function pageTitle(){const t=$('.tab.active')?.textContent||'Today'; $('#pageTitle').textContent=t}
$('#tabs').addEventListener('click',e=>{if(!e.target.matches('.tab'))return; $$('.tab').forEach(b=>b.classList.remove('active')); e.target.classList.add('active'); $$('.view').forEach(v=>v.classList.remove('active')); $('#'+e.target.dataset.view).classList.add('active'); pageTitle()});
function costPerDose(v){const mg=num(v.amountMg), cost=num(v.cost), doseMg=num(v.doseMcg)/1000; return mg&&cost&&doseMg ? (cost/mg)*doseMg : 0}
function remainingValue(v){const mg=num(v.amountMg), rem=num(v.remainingMg), cost=num(v.cost); return mg&&cost ? cost*(rem/mg) : 0}
function dosesLeft(v){const rem=num(v.remainingMg), dose=num(v.doseMcg)/1000; return rem&&dose ? Math.floor(rem/dose) : 0}
function render(){
 const spend=db.vials.reduce((a,v)=>a+num(v.cost),0), value=db.vials.reduce((a,v)=>a+remainingValue(v),0), doses=db.vials.reduce((a,v)=>a+dosesLeft(v),0);
 $('#statMode').textContent=db.settings.delivery||'—'; $('#statVials').textContent=db.vials.length; $('#statSpend').textContent=money(spend); $('#statValue').textContent=money(value); $('#statDoses').textContent=doses; $('#statFood').textContent=db.foods.length;
 const today=new Date().toISOString().slice(0,10); const due=db.schedule.filter(s=>s.date===today); $('#todayBox').innerHTML=due.length?due.map(s=>`<div class="item"><b>${vialName(s.vialId)}</b><span>${s.time||''} • ${s.amountMcg||'—'} mcg • ${s.site||'site not set'} • ${s.status}</span></div>`).join(''):'No schedule entries due today.';
 $('#scheduleVial').innerHTML='<option value="">Choose item</option>'+db.vials.map(v=>`<option value="${v.id}">${esc(v.name)}</option>`).join('');
 $('#vialList').innerHTML=db.vials.map(v=>`<article class="item"><div class="item-head"><b>${esc(v.name)}</b><button onclick="del('vials','${v.id}')">Delete</button></div><div><span class="pill">${esc(v.type||'Item')}</span><span class="pill">${money(v.cost)}</span><span class="pill">${dosesLeft(v)} doses left</span><span class="pill">${money(costPerDose(v))}/dose</span></div><small>${num(v.remainingMg)}mg remaining • value ${money(remainingValue(v))} • batch ${esc(v.batch||'—')} • expiry ${esc(v.expiry||'—')}</small><p>${esc(v.notes||v.storage||'')}</p></article>`).join('')||'<div class="empty">No vials/items yet.</div>';
 $('#scheduleList').innerHTML=db.schedule.sort((a,b)=>(a.date+a.time).localeCompare(b.date+b.time)).map(s=>`<article class="item"><div class="item-head"><b>${esc(vialName(s.vialId))}</b><button onclick="del('schedule','${s.id}')">Delete</button></div><span>${s.date} ${s.time} • ${s.amountMcg||'—'} mcg • ${s.site||'—'} • ${s.status}</span><small>Cost: ${money(s.actualCost||autoCost(s))}</small><p>${esc(s.notes||'')}</p></article>`).join('')||'<div class="empty">No schedule entries.</div>';
 $('#weightList').innerHTML=db.weights.sort((a,b)=>b.date.localeCompare(a.date)).map(w=>`<article class="item"><b>${w.date}: ${w.weight}${w.unit}</b><span>Appetite: ${w.appetite||'—'} • Waist: ${w.waist||'—'}</span><p>${esc(w.notes||'')}</p></article>`).join('')||'<div class="empty">No weight entries.</div>';
 $('#foodList').innerHTML=db.foods.sort((a,b)=>b.date.localeCompare(a.date)).map(f=>`<article class="item"><b>${f.date}: ${esc(f.meal)}</b><span>Severity ${f.severity||0}/10 • symptoms: ${esc(f.symptoms||'none')}</span><small>${f.portion} portion • fatty ${f.fatty} • spicy ${f.spicy} • caffeine ${f.caffeine}</small><p>${esc(f.notes||'')}</p></article>`).join('')||'<div class="empty">No food entries.</div>';
 $('#logList').innerHTML=db.logs.sort((a,b)=>b.date.localeCompare(a.date)).map(l=>`<article class="item"><b>${l.date}</b><span>Appetite ${l.appetite||'—'} • nausea ${l.nausea||'—'} • energy ${l.energy||'—'} • ${l.digestion||'—'}</span><p>${esc(l.notes||'')}</p></article>`).join('')||'<div class="empty">No daily logs.</div>';
 $('#compoundList').innerHTML=db.compounds.map(c=>`<article class="item"><div class="item-head"><b>${esc(c.name)}</b><button onclick="del('compounds','${c.id}')">Delete</button></div><span>${esc(c.purpose||'Additional tracking')}</span><p>${esc(c.notes||'')}</p></article>`).join('')||'<div class="empty">No additional compounds tracked.</div>';
 $('#foodInsights').innerHTML=insights();
}
function vialName(i){return db.vials.find(v=>v.id===i)?.name||'Unassigned'} function autoCost(s){const v=db.vials.find(v=>v.id===s.vialId); return v?costPerDose(v):0} function esc(s){return String(s||'').replace(/[&<>]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;'}[m]))}
window.del=(k,i)=>{db[k]=db[k].filter(x=>x.id!==i);save()}
$('#settingsForm').addEventListener('submit',e=>{e.preventDefault();db.settings={...db.settings,...formObj(e.target)};save()});
$('#vialForm').addEventListener('submit',e=>{e.preventDefault();const o=formObj(e.target);db.vials.push({...o,id:id()});e.target.reset();save()});
$('#scheduleForm').addEventListener('submit',e=>{e.preventDefault();const o=formObj(e.target);db.schedule.push({...o,id:id()});e.target.reset();save()});
$('#weightForm').addEventListener('submit',e=>{e.preventDefault();db.weights.push({...formObj(e.target),id:id()});e.target.reset();save()});
$('#foodForm').addEventListener('submit',e=>{e.preventDefault();db.foods.push({...formObj(e.target),id:id()});e.target.reset();save()});
$('#logForm').addEventListener('submit',e=>{e.preventDefault();db.logs.push({...formObj(e.target),id:id()});e.target.reset();save()});
$('#compoundForm').addEventListener('submit',e=>{e.preventDefault();db.compounds.push({...formObj(e.target),id:id()});e.target.reset();save()});
$('#calcBtn').addEventListener('click',()=>{const mg=num($('#calcMg').value), water=num($('#calcWater').value), dose=num($('#calcDose').value); if(!mg||!water||!dose){$('#calcResult').textContent='Enter all three values.';return} const concMcgMl=mg*1000/water, ml=dose/concMcgMl, units=ml*100; $('#calcResult').innerHTML=`<b>Concentration:</b> ${concMcgMl.toFixed(2)} mcg/ml<br><b>Volume to measure:</b> ${ml.toFixed(4)} ml<br><b>U-100 syringe:</b> ${units.toFixed(1)} units`;});
$$('.body-map button').forEach(b=>b.addEventListener('click',()=>{$('#selectedSite').textContent=b.dataset.site+' copied to schedule.'; $('#siteInput').value=b.dataset.site;}));
function insights(){if(db.foods.length<3)return 'Add at least 3 food entries to see simple repeated pattern hints.'; const flags={fatty:0,spicy:0,caffeine:0}; db.foods.forEach(f=>{if(num(f.severity)>=5){if(f.fatty==='Yes')flags.fatty++; if(f.spicy==='Yes')flags.spicy++; if(f.caffeine==='Yes')flags.caffeine++;}}); const out=Object.entries(flags).filter(([,v])=>v>0).map(([k,v])=>`<div class="item"><b>Possible ${k} link</b><span>${v} higher-severity symptom entries included ${k} intake.</span></div>`); return out.join('')||'No repeated high-severity food markers yet.'}
function download(name,text,type='application/json'){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([text],{type}));a.download=name;a.click();URL.revokeObjectURL(a.href)}
$('#exportJson').addEventListener('click',()=>download('vialwise-backup.json',JSON.stringify(db,null,2)));
$('#exportCsv').addEventListener('click',()=>{let rows=['section,date,name,amount,cost,notes'];db.vials.forEach(v=>rows.push(`vial,,"${v.name}","${v.amountMg}mg",${v.cost||0},"${v.notes||''}"`));db.schedule.forEach(s=>rows.push(`schedule,${s.date},"${vialName(s.vialId)}","${s.amountMcg}mcg",${s.actualCost||autoCost(s)},"${s.notes||''}"`));db.weights.forEach(w=>rows.push(`weight,${w.date},weight,"${w.weight}${w.unit}",,"${w.notes||''}"`));download('vialwise-summary.csv',rows.join('\n'),'text/csv')});
$('#sampleBtn').addEventListener('click',()=>{db.vials=[{id:'v1',name:'GLP-1 vial',type:'GLP-1',amountMg:'10',waterMl:'2',remainingMg:'8.5',doseMcg:'250',cost:'85',batch:'Demo',expiry:'2026-12-01',notes:'Demo only'}];db.schedule=[{id:'s1',vialId:'v1',date:new Date().toISOString().slice(0,10),time:'09:00',amountMcg:'250',site:'Left abdomen',status:'Planned',notes:'Demo entry'}];db.foods=[{id:'f1',date:new Date().toISOString().slice(0,10),meal:'Coffee and toast',portion:'Small',fatty:'No',spicy:'No',caffeine:'Yes',symptoms:'mild nausea',severity:'3'}];save()});
$('#clearBtn').addEventListener('click',()=>{if(confirm('Clear all local VialWise data?')){localStorage.removeItem(KEY);location.reload()}});
render();
